[package]
name = "QLearning"
version = "0.1.0"
authors = ["Mer Agens <self@meredithagens.com>"]

[dependencies]
rurel = "0.1.2"
rand = "0.5.4"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"